### ISSUE TITLE
Prometheus alertmanager receiver

### ISSUE THREAD

**Issue by almereyda** [matrix-org/go-neb#140]
I am interested in aggregating development related events from our GitLab and Prometheus instance into a Matrix channel.
Basic notification level in a right-side bar in Riot, as in https://github.com/vector-im/riot-web/issues/2484, is additionally desired.

If one doesn't intend to use the [webhook interface](https://prometheus.io/docs/alerting/configuration/#webhook-receiver-<webhook_config>) of their alertmanager via [Hello Matrix](https://logfile.ch/collaboration/tech/2016/11/18/hello-matrix-hello-webhooks/), would/should one rather create a Matrix receiver there or push forward https://github.com/matrix-org/matrix-appservice-bridge/issues/6?

---

Another way could be to focus on https://github.com/matrix-org/go-neb/issues/96 first, which would quickly involve the Hubot ecosystem, and with it also tackle https://github.com/matrix-org/go-neb/issues/127 on the way.

**Comment by aviraldg** [comment]
finishing and merging #116 will solve this as well

**Comment by turt2live** [comment]
This was done in https://github.com/matrix-org/go-neb/pull/249
