### ISSUE TITLE
RSS: feed including ä in domain cannot be added

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/go-neb#145]
* http://hän.fi/feed/ ==> `HTTP 500: Failed to register service: Failed to read URL http://hän.fi/feed/: Get http://h%C3%A4n.fi/feed/: dial tcp: lookup hän.fi: invalid domain name`

http://xn--hn-via.fi/feed appears to work, but I don't know until feed items appear or don't appear, but do users know that if browsers (Firefox 51) don't tell it and I had to do a few searxes until figuring out how to get that format.

**Comment by Kegsay** [comment]
> but I don't know until feed items appear or don't appear

It should fail to register the feed URL and display an error to you. Is it not?

The form you're using is punycode, since domain names don't allow arbitrary UTF-8. It looks like the Go standard library does not understand punycode. We'll need to add a wrapper for it.

**Comment by Kegsay** [comment]
Looks like Go 1.8 does: https://github.com/golang/go/issues/13686 - so this will be fixed when Go 1.8 is released in Feb.

**Comment by Mikaela** [comment]
> It should fail to register the feed URL and display an error to you. Is it not?

It doesn't, but there also isn't any mark of it succeeding such as showing the last feed item in the manage integrations view or posting it to the room or anything.

**Comment by Kegsay** [comment]
> It doesn't

When I try it, I get the following red error message:

```
HTTP 500: Failed to register service: Failed to read URL http://hän.fi/feed/: Get http://h%C3%A4n.fi/feed/: dial tcp: lookup hän.fi: invalid domain name
```

Are there any errors in the developer console when you try to add this URL?

**Comment by Mikaela** [comment]
```
RssBotComponent.js:79 Subscribing to http://hän.fi/feed/
ScalarMessaging.js:136 Action:membership_state failed with message: Must be viewing a roomo @ ScalarMessaging.js:136I @ ScalarMessaging.js:322
RssBotComponent.js:79 Subscribing to http://hän.fi/feed/
ScalarMessaging.js:136 Action:membership_state failed with message: Must be viewing a roomo @ ScalarMessaging.js:136I @ ScalarMessaging.js:322
```

And now I don't get even error in the interface, the feed just doesn't get added.

**Comment by Kegsay** [comment]
Interesting, how are you opening the Scalar interface? Via "Manage Integrations"? On `/develop`? Browser?

**Comment by Mikaela** [comment]
Manage integrations on riot-desktop installed from AUR on Arch Linux.

**Comment by Mikaela** [comment]
It seems that the bot threw two old seeming items yesterday, I don't know if it's related to this issue or if something was wrong with the feed.

```
Yesterday
RSS Bot [@Ciblia:matrix.org]
Valta on hajautettava posted a new article: Piraattien puoluerekisterihakemus on kohta valmis! ( http://xn--hn-via.fi/2016/02/22/piraattien-puoluerekisterihakemus-on-kohta-valmis/ )
Valta on hajautettava posted a new article: Olen ehdokkaana HESYn hallitukseen huhtikuun lopussa ( http://xn--hn-via.fi/2016/02/28/olen-ehdokkaana-hesyn-hallitukseen-huhtikuun-lopussa/ )
```

2017-03-11 18:59+0200

**Comment by Kegsay** [comment]
This issue won't affect items in the RSS feed, only whether it can read the feed or not. Waiting for a bugfix patch to Go 1.8 before updating our production systems.

**Comment by Kegsay** [comment]
I moved Go-NEB to a different machine today which runs Go 1.8.x - and this now works :)
