### ISSUE TITLE
Gitter: Bot can't be removed from channel

### ISSUE THREAD

**Issue by TheJJ** [matrix-org/go-neb#153]
In our channel (#sfttech:matrix.org), we tried the gitter integration bot from matrix, but aborted it as it could not be paired up with gitter correctly. Now the bot sits in the channel and can't be removed, as it has admin rights.

The gitter integration is not shown, but the bot is there.

**Comment by Kegsay** [comment]
Gitter is not the responsibility of Go-NEB, but I have passed this on to the relevant project. Thanks.

**Comment by TheJJ** [comment]
And where is the relevant project? :)

**Comment by Kegsay** [comment]
It's not a public project.

**Comment by chevdor** [comment]
@Kegsay Could you forward to the "relevant project" that this issue is indeed still present and rather annoying? :)

**Comment by ara4n** [comment]
@Half-Shot one for you.

**Comment by TheJJ** [comment]
On a side-note, the gitter bot is still in #sfttech:matrix.org and can't be removed :wink:

**Comment by Half-Shot** [comment]
@TheJJ What's your matrix id?

**Comment by Half-Shot** [comment]
(In this instance the gitter bot wasn't doing anything, so I kicked it manually)
