### ISSUE TITLE
Bots don't work in encrypted rooms

### ISSUE THREAD

**Issue by rxl881** [matrix-org/go-neb#157]
The bots are not currently able to react to commands in encrypted rooms (and it's not obvious to users why they are not responding).

From discussion with @Kegsay, bots won't be able to work in encrypted rooms until Olm support is added to gomatrix (which appears to be a way out).

In the short term I suggest modifying the bots to display an error message or prevent them from being invited in to an encrypted chat, so that the user at least isn't confused as to why the bots aren't responding.

**Comment by uhoreg** [comment]
https://github.com/vector-im/riot-web/issues/2277 is the riot-web issue for this

**Comment by Kegsay** [comment]
In order for gomatrix to support this you'll need to use [cgo](https://golang.org/cmd/cgo/).

**Comment by MTRNord** [comment]
@Kegsay there is a gomatrix issue that says there is olm for go wouldn't that be possible to use? instead of using a C lib. https://github.com/matrix-org/gomatrix/issues/31
