### ISSUE TITLE
#3dprinting should not match issue #3 (github)

### ISSUE THREAD

**Issue by turt2live** [matrix-org/go-neb#170]
![image](https://cloud.githubusercontent.com/assets/1190097/24615106/980a4d4c-184a-11e7-8e77-1dad94c2d26a.png)

The assistance is appreciated, however `#3dprinting` appears to be a bit too lenient on the regex.

**Comment by t3chguy** [comment]
Best regex I conjured for this and to fix things like `t3chguy#21412` (without org/repo format) was `((([A-z0-9-_.]+)/([A-z0-9-_.]+))|\B)#([0-9]+)(?: |$)`

**Comment by t3chguy** [comment]
or better yet, `(?:(?:([A-z0-9-_.]+)/([A-z0-9-_.]+))|\B)#([0-9]+)(?:$|[ )])` but this will require a small refactor to the matchingGroups consumers

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/35338991-4071c8d8-0117-11e8-8a61-1bd648f3fd42.png)

Current regex matches two of the test cases wrongly: 
![image](https://user-images.githubusercontent.com/2403652/35339012-535eae7a-0117-11e8-948d-0ad151332721.png)
