### ISSUE TITLE
Cannot add new RSS feeds when an existing feed is 404ing

### ISSUE THREAD

**Issue by turt2live** [matrix-org/go-neb#173]
Situation:
I have multiple Jenkins jobs being fed to the RSS bot. While restructuring the Jenkins jobs, some of the feed URLs changed. I can no longer remove those 'broken' feeds, and I can't add new feeds to the bot.

**Comment by Kegsay** [comment]
Dupe https://github.com/matrix-org/go-neb/issues/128 - Perhaps @rxl881 can look into this since I appreciate this is frustrating.
