### ISSUE TITLE
Configure whether go-neb sends messages to a room as notice or msg

### ISSUE THREAD

**Issue by ara4n** [matrix-org/go-neb#183]
IRC-bridged folks may object to bots sending automated updates as notices rather than privmsgs.

In practice, all my bots ever have used NOTICE (since the days of eggdrop) to clearly mark them as automated traffic.  But apparently notices get treated as highlights on some IRC clients - c.f. https://phabricator.wikimedia.org/T101575 and:

```
<luciferMysticus (IRC)>
the RFCs say that NOTICE is supposed to be used for *private* messages that should not trigger an automatic response from bots
```

etc.

So, we probably should make it configurable per-room based on the tastes of the community as to whether bots should send their stuff as notices or msgs or not.

We might want to do this on matrix-appservice-irc instead, actually, given notices in Matrix are used almost exclusively for bot-generated messages - so arguably this is a confused impedance mismatch on how matrix-notices should be bridged to irc-notices (or not).

**Comment by Mikaela** [comment]
The RFC says nothing about private that I could see:

```
4.4.2 Notice

      Command: NOTICE
   Parameters: <nickname> <text>

   The NOTICE message is used similarly to PRIVMSG.  The difference
   between NOTICE and PRIVMSG is that automatic replies must never be
   sent in response to a NOTICE message.  This rule applies to servers
   too - they must not send any error reply back to the client on
   receipt of a notice.  The object of this rule is to avoid loops
   between a client automatically sending something in response to
   something it received.  This is typically used by automatons (clients
   with either an AI or other interactive program controlling their
   actions) which are always seen to be replying lest they end up in a
   loop with another automaton.

   See PRIVMSG for more details on replies and examples.
```

* https://tools.ietf.org/html/rfc1459#section-4.4.2

It doesn't need a lot of `!echo @echo` looping to see why NOTICE usage might be desirable for channels. 

However I have also got feedback about the RSS bot using notices and I linked them to the RFC and GO-NEB and matrix-appservice-irc saying that I am not running either and that the behaviour is unlikely to change as it's in spirit of the RFC and Matrix which doesn't ping on NOTICEs by default.

**Comment by uhoreg** [comment]
Wouldn't it be better to be able to configure the bridge to tell it how to translate `m.notice`, since this issue is likely to affect all bots in the room?

**Comment by Kegsay** [comment]
As multiple people have said, this is not specific to Go-NEB but is an IRC bridge thing. Migrating issue.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-appservice-irc/issues/471
