### ISSUE TITLE
CA-certificates in Docker image

### ISSUE THREAD

**Issue by joenas** [matrix-org/go-neb#190]
Using `https` isn't working because missing certificates. 
Add something like this to `Dockerfile`: 

`RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*`
 (from https://hub.docker.com/r/octoblu/alpine-ca-certificates/~/dockerfile/)

**Comment by Kegsay** [comment]
@superdump does this sound sane?

**Comment by d2dyno** [comment]
This can be closed: https://github.com/matrix-org/go-neb/blob/master/Dockerfile#L23
