### ISSUE TITLE
Go version mismatch

### ISSUE THREAD

**Issue by turt2live** [matrix-org/go-neb#204]
The README claims Go 1.5+, but the project requires Go 1.7+ to build due to an import somewhere for "context".

**Comment by t3chguy** [comment]
lol it claims both:
![image](https://user-images.githubusercontent.com/2403652/30612802-a4609728-9d7d-11e7-9acb-44c2bb0225b7.png)

**Comment by turt2live** [comment]
fwiw I also couldn't get it to work with 1.7 or 1.8. I had to use 1.9. Although I'm comfortable writing that off as my fault and not a fault of the project.

As for the conflicting version requirement: I didn't even see that one until now. I skipped right ahead to clicking "Installing" on the readme.

**Comment by Kegsay** [comment]
It needs 1.7 due to one of its dependencies use of HTTP request contexts. Fixed contradiction in README.
