### ISSUE TITLE
!github react error message says you need to log into Github before you can *create* issues

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/go-neb#211]
which is confusing since they're not trying to create an issue (as seen at https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$15120727014403316wXkqI:matrix.org)

**Comment by t3chguy** [comment]
I think it just needs redeploying: https://github.com/matrix-org/go-neb/blob/master/src/github.com/matrix-org/go-neb/services/github/github.go#L252-L256
