### ISSUE TITLE
The response to !github help is illegible

### ISSUE THREAD

**Issue by ara4n** [matrix-org/go-neb#226]
Surely this should be on separate lines rather than a massive indigestible oneliner

**Comment by tgr** [comment]
![screenshot](https://matrix.org/_matrix/media/v1/download/matrix.org/XfNpnAycRaAGucuSWEwGovxf)

Having the emojis displayed as such is not helpful either (or are those meant to be actually input to the bot as emojis?)

**Comment by ara4n** [comment]
yes, they are a shorthand alternative to the long form “heart” etc

**Comment by aaronraimist** [comment]
![screen shot 2019-02-09 at 12 42 22 pm](https://user-images.githubusercontent.com/5855073/52524930-27f37b80-2c68-11e9-9538-aded93cede08.png)

This is fixed
