### ISSUE TITLE
(RSS) YouTube Playlists don't work

### ISSUE THREAD

**Issue by Nobabs27** [matrix-org/go-neb#237]
RSS from YouTube playlists do not work.
For example:
`https://www.youtube.com/feeds/videos.xml?playlist_id=[valid playlist id]`
Or this alternative that I heard about that also does not work:
`http://morning-retreat-1911.herokuapp.com/feed/playlist.php?id=[valid playlist id]`

The feeds show up fine in Firefox.
Any ideas?

**Comment by MTRNord** [comment]
The upper one is an ATOM feed and afaik thats not supported yet by go-neb. Only rss is. I think #235 is related

**Comment by MTRNord** [comment]
The second one is RSS and should work. On that one I am not sure why. maybe it isnt valid

**Comment by MTRNord** [comment]
@Nobabs27 yes the feeds are valid. But go-neb doesn't support the one format. one is an RSS feed and the other one an Atom feed. I am not sure why the RSS one fails but the Atom one is not supported yet

**Comment by Nobabs27** [comment]
Actually the second (RSS) one does work, it just doesn't outpute anything right away, it waits until anything new.....
Even though I tested with my own playlist, I guess it just takes a while.
