### ISSUE TITLE
Github bot created a duplicate issue

### ISSUE THREAD

**Issue by tulir** [matrix-org/go-neb#263]
https://matrix.to/#/!FVLTSqqprVFuSODoFc:maunium.net/$15498874304756wbJHW:maunium.net?via=maunium.net&via=matrix.org&via=ponies.im

![image](https://user-images.githubusercontent.com/4224639/52562938-b9015880-2e08-11e9-8892-df99cd61c442.png)

**Comment by redsky17** [comment]
This just happened to me in #nheko-reborn as well.

**Comment by richvdh** [comment]
looks like @ara4n restarted it to fix this

**Comment by tulir** [comment]
This probably shouldn't be closed after just restarting, the actual bug won't go anywhere with a restart.

**Comment by turt2live** [comment]
Opened an issue for the cause: https://github.com/matrix-org/go-neb/issues/268
