### ISSUE TITLE
rss integration app not working

### ISSUE THREAD

**Issue by daurigi** [matrix-org/go-neb#279]
After the security issue of 11 Apr, the rss integration app stopped working. After a number of days the service became operational again, until it stopped working for me on 18 Apr midday-ish.

I havent changed anything in terms of configuration. My homeserver is matrix.org.

Unfortunately I cant be more specific than this.

**Comment by jaywink** [comment]
Hi @daurigi . Since 4 days have passed over Easter, did your issue resolve? If not, can you maybe DM me with some more details like room ID so I can have a look, thanks. My Matrix ID is `@jaywink:federator.dev`.

**Comment by ara4n** [comment]
there are more reports that this is wedged from HQ (francis)

**Comment by jaywink** [comment]
Some RSS feeds at least work, [this is proof of that](https://matrix.to/#/!gkpqsseYVzWQkWeBmU:matrix.org/$1556058467913695XFPah:matrix.org?via=matrix.org&via=federator.dev&via=matrix.webzone69.com).

I'll restart for fun and profit anyway. But for debugging would be useful to know problematic room ID's.

**Comment by jaywink** [comment]
@daurigi issue should be now resolved, can you confirm?

**Comment by jaywink** [comment]
Closing for now at least as no further reports received. Please shout here if issues still persist! Thanks for reporting.
