### ISSUE TITLE
GitHub bot reads edits as new messages

### ISSUE THREAD

**Issue by babolivier** [matrix-org/go-neb#290]
Writing a message containing an issue number like `#XXXX`, then editing the message, make the bot send twice the description of the issue.

![image](https://user-images.githubusercontent.com/5547783/58946162-36b4ef80-877d-11e9-9466-7614346aba04.png)

The event we can see between the two notices is the edit.

**Comment by turt2live** [comment]
Duplicate of https://github.com/matrix-org/go-neb/issues/289

**Comment by babolivier** [comment]
This is actually the reverse of #289: there the issue is that the bot doesn't process the edit, here the issue is that the bot processes it too much. So related but not a duplicate.

**Comment by turt2live** [comment]
The bot doesn't support edits at all, so we need a canonical issue for that. I don't think we need several issues to track the same feature that doesn't exist.

**Comment by babolivier** [comment]
Fair enough
