### ISSUE TITLE
build with go 1.13.3 fails with can't find import: "golang.org/x/text/transform"

### ISSUE THREAD

**Issue by dwayneem** [matrix-org/go-neb#303]
dwayne@localhost:~/work$ git clone https://github.com/matrix-org/go-neb
Cloning into 'go-neb'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 7378 (delta 10), reused 27 (delta 8), pack-reused 7342
Receiving objects: 100% (7378/7378), 10.93 MiB | 19.56 MiB/s, done.
Resolving deltas: 100% (2683/2683), done.
dwayne@localhost:~/work$ cd go-neb
dwayne@localhost:~/work/go-neb$ gb build github.com/matrix-org/go-neb
# golang.org/x/text/runes
cond.go:10:2: can't find import: "golang.org/x/text/transform"
github.com/matrix-org/go-neb/api
github.com/Sirupsen/logrus
github.com/matrix-org/gomatrix
github.com/beorn7/perks/quantile
github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
github.com/prometheus/common/model
github.com/prometheus/procfs
github.com/mattn/go-shellwords
github.com/google/go-querystring/query
golang.org/x/net/context
github.com/matrix-org/go-neb/realms/jira/urls
github.com/die-net/lrucache
github.com/gregjones/httpcache
golang.org/x/net/html/atom
github.com/mmcdole/gofeed/extensions
github.com/mmcdole/goxpp
golang.org/x/text/encoding/internal/identifier
golang.org/x/text/internal/utf8internal
golang.org/x/text/internal/tag
github.com/shurcooL/sanitized_anchor_name
github.com/golang/protobuf/proto
gopkg.in/yaml.v2
# golang.org/x/text/encoding
encoding.go:20:2: can't find import: "golang.org/x/text/transform"
github.com/matrix-org/dugong
github.com/matrix-org/util
github.com/matrix-org/go-neb/types
github.com/andygrunwald/go-jira
golang.org/x/oauth2/internal
github.com/dghubble/oauth1
github.com/google/go-github/github
golang.org/x/text/language
golang.org/x/net/html
github.com/prometheus/client_model/go
github.com/matttproud/golang_protobuf_extensions/pbutil
github.com/russross/blackfriday
github.com/matrix-org/go-neb/services/echo
github.com/matrix-org/go-neb/database
github.com/matrix-org/go-neb/services/giphy
github.com/matrix-org/go-neb/services/google
github.com/matrix-org/go-neb/services/guggy
github.com/matrix-org/go-neb/services/imgur
golang.org/x/oauth2
github.com/matrix-org/go-neb/services/github/webhook
github.com/andybalholm/cascadia
github.com/jaytaylor/html2text
github.com/prometheus/common/expfmt
github.com/matrix-org/go-neb/services/slackapi
github.com/matrix-org/go-neb/matrix
github.com/matrix-org/go-neb/services/alertmanager
github.com/matrix-org/go-neb/services/travisci
github.com/matrix-org/go-neb/realms/jira
github.com/matrix-org/go-neb/services/github/client
github.com/PuerkitoBio/goquery
github.com/matrix-org/go-neb/services/wikipedia
github.com/prometheus/client_golang/prometheus
github.com/matrix-org/go-neb/services/jira/webhook
github.com/matrix-org/go-neb/realms/github
github.com/matrix-org/go-neb/metrics
github.com/matrix-org/go-neb/services/jira
github.com/matrix-org/go-neb/services/github
github.com/matrix-org/go-neb/clients
github.com/matrix-org/go-neb/polling
github.com/matrix-org/go-neb/api/handlers
github.com/mattn/go-sqlite3
FATAL: command "build" failed: exit status 2
dwayne@localhost:~/work/go-neb$ go version
go version go1.13.3 linux/amd64

**Comment by dwayneem** [comment]
Builds fine with go 1.10.3, but not the latest 1.13.3 - Have not yet tried any versions of go in between.

**Comment by skynet0590** [comment]
I got the same error. Event if I change to go 1.10.3 or 1.12.12. It still be error with this
```
skynet@vietanhPC:~/GoModule/go-neb$ gb build github.com/matrix-org/go-neb
# golang.org/x/text/runes
cond.go:10:2: can't find import: "golang.org/x/text/transform"
# golang.org/x/text/encoding
encoding.go:20:2: can't find import: "golang.org/x/text/transform"
FATAL: command "build" failed: exit status 2

```
