### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/go-neb#326]
I saw green and happiness in https://github.com/matrix-org/go-neb/pull/322 but in reality it was very badly broken. Whilst we do have tests for services, we don't have testing around the bot framework itself. We should really add this to prevent humans making mistakes.

Specifically, a fake homeserver for Go-NEB to send `/sync` requests to as well as configuring via the HTTP API e.g `/configureClient` should do it. We're not interested in testing any specific service, so just the echo service will do.

**Comment by nikofil** [comment]
How would the fake homeserver work? Could we spin up a docker container with Synapse for that?

**Comment by nikofil** [comment]
I'd like to take this one, please assign to me if you don't mind.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/go-neb/blob/master/goneb_services_test.go#L26 is probably a good enough starting point.

**Comment by nikofil** [comment]
That test was very useful, I put my tests in that file too. The encrypted room one is kinda messy, I opted to skip the whole session negotiation and just put the megolm sessions in the store directly to prevent from becoming a lot messier.
