### ISSUE TITLE
 Device ID is not set which will result in E2E encryption/decryption not working 

### ISSUE THREAD

**Issue by r3k2** [matrix-org/go-neb#328]
so I did a git pull from master etc to run go-neb with out the proxy since I notice you guys have closed the ticket to enable e2ee as done.
but I get this when loggin in:
```
 Device ID is not set which will result in E2E encryption/decryption not working 
```
where do I add this to the config? seems the wiki has not been updated to any new settings?

Thanks

**Comment by nikofil** [comment]
You're right, I forgot to add some docs with the PR that does the change. I was preparing another PR that would include that, but it would take some time so I've gone ahead and made a small PR just for that now.

(You can put a line `DeviceID: THE_ID` below your `AccessToken` line.)
