### ISSUE TITLE
"failed to decrypt megolm event: no session with given ID found"

### ISSUE THREAD

**Issue by r3k2** [matrix-org/go-neb#332]
Only recently I started to get this msg on the RSS posts, it was working fine after adding the ID to the config for the e2ee and then it broke.
```
"failed to decrypt megolm event: no session with given ID found"
```

**Comment by nikofil** [comment]
This error msg is by neb, right? This is when it can't decrypt an incoming message. Is it when someone else writes in that room that it appears?

Were you doing anything when it broke? Like maybe someone left the room at that time - otherwise the session should have stayed the same. Did you maybe restart the bot with a new DB causing it to lose its sessions?

**Comment by r3k2** [comment]
@nikofil yes error is output to channel by the neb bot, is when RSS output since is the only thing we use the bot for, I did move it from one server to another and start it the binary there.

**Comment by nikofil** [comment]
I see, were they using a shared database? If not the sessions were lost on the move. You can force a new session to start by having a device leave and re-join the room so that neb gets the room key again.

**Comment by r3k2** [comment]
@nikofil no, I just stop it and run it on the other server, like if it was the first time *it should* just realice is the first time and just do its thing I do not see why I have to do anything at all, as far as the bot code goes is a new run... if there is no .db it should re get all keys... about your hack of re-joining I cant tell the 100+ users in the room to re-join...

**Comment by nikofil** [comment]
They don't need to all rejoin, one should be enough. The other (probably better) option is to log in again with neb and get a new session and device ID for it and change that in the config, as then the other devices in the room have to share their keys with it again. If they already have shared their key with a device they won't do it again, that's how the protocol is to avoid anyone to be able to decrypt messages they shouldn't be able to see.

**Comment by r3k2** [comment]
@nikofil ok this ha fix it:
```
1. stop bot
2. change device ID
3. change device name
4. wipe .db
5. start bot
```

Thanks for your help.
