### ISSUE TITLE
GH oauth silently failed; popup appeared and then instantly vanished

### ISSUE THREAD

**Issue by ara4n** [matrix-org/go-neb#42]
leaving you stranded in scalar-web and having to hit back button in the iframe

**Comment by Kegsay** [comment]
Are you sure it failed?

**Comment by Kegsay** [comment]
I believe it doesn't fail, but the screen doesn't update after it auths you (so you need to back out and go back in), which I believe is what you're describing.

**Comment by Kegsay** [comment]
Now fixed.
