### ISSUE TITLE
RSS: https://apod.nasa.gov/apod.rss doesn't work.

### ISSUE THREAD

**Issue by aliencq** [matrix-org/go-neb#90]
It's over 24h already since it was added via integration UI, but still nothing.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/go-neb/commit/299164d525d860dc80c2cd0e5dba26e77497f86d - Will add a tracker myself and close this when I can confirm that this feed is now working. Thanks for your patience :)

**Comment by aliencq** [comment]
Thank you, waiting for a new post :)

**Comment by aliencq** [comment]
It works now.

**Comment by Kegsay** [comment]
Works for me too \o/ Pretty!
